### ISSUE TITLE
improve list layout for small viewport widths

### ISSUE THREAD

**Issue by tarnas14** [tarnas14/ti4-companion#96]
right now on small widths the list with "full access" badge looks bad:

![1636892718486](https://user-images.githubusercontent.com/9142942/141680980-1eee14e1-c1ad-4575-9eb5-fa290ebe8b49.png)

propose and implement a better layout for small screen sizes

leave the wide layout as it is :)

**Comment by sjblurton** [comment]
![Screenshot-for-ui-update](https://user-images.githubusercontent.com/62861470/141685600-2fc68a53-110e-48f2-9023-716d5a775c02.png)

moving the list orientation on small screens? 

Or do you mean the tick doesn't really mean full access and you want a better icon? With the right icon the text wouldn't be needed... Though i thing sorting in to columns instead of rows looks better
![Uploading Screenshot-for-ui-update.png…]()


If i'm on the right lines i can implement quickly.

**Comment by sjblurton** [comment]
![Screenshot-for-ui-update](https://user-images.githubusercontent.com/62861470/141687566-12217c52-cf89-48ca-b2dc-26da79fa7abe.png)

sorry, second image didn't upload...

**Comment by tarnas14** [comment]
hi! thank you for contribution, I wasn't clear enough in the issue, I jotted it down and wanted to go back to it ^^

yes, I think for smaller widths the "full access" badge needs to flow below the session data, maybe we can also change the label from "full access" to "\/ edit" or something?
